version: '3'

services:
  nginx:
    build:
      context: '.'
      dockerfile: 'nginx/Dockerfile'
    depends_on:
    - python
    network_mode: 'service:python' # use network interface of python container to simulate awsvpc network mode
  python:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
    - '8080:80' # forwards port of nginx container
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: app
      DATABASE_USER: app
      DATABASE_PASSWORD: secret
      SECRET_KEY: secret